### ISSUE TITLE
Reporting Data has incorrect column associations to frame

### ISSUE THREAD

**Issue by toddpi314** [autonomio/talos#146]
- [x] I'm up-to-date with the latest release:
    
      pip install -U talos

- [x] I've confirmed that my Keras model works outside of Talos.

-------------------------------------------------------------------------

I noticed that after scanning a Parameter dictionary, the inner data object of the Reporter has the column/row associations incorrectly ordered in Python 2.7.

For example, something like:
``` python
p = {
        'compile_loss': ['mean_squared_error'], 
        'compile_optimizer': ['sgd'], 
        'hidden_units': [64, 128, 512],
        'inner_activation': ['relu'],
        'output_activation': ['relu'], 
        'recurrent_activation': ['relu'],
        'lstm_layers': [0],
        'gru_layers': [0],
        'dropout_ratio': [.2],
        'activate_regularizers': [1, 0],
        'batch_window_size': [ 5, 50 ],
        'epochs': [ 100 ]
    }

    scan = ta.Scan(train_inputs, train_outputs, p, self._create_keras_model)
    reporting = ta.Reporting(scan)
    print(reporting.data.columns)
```

Prints out:
``` bash
   round_epochs                  acc         loss              val_acc  \
1           10  0.20000000298023224  315008640.0  0.20000000298023224   
2           10  0.30000001192092896  170956672.0  0.20000000298023224   

      val_loss    lr recurrent_activation inner_activation  \
1  308987328.0  0.01                  0.2             relu   
2  169688720.0  0.01                  0.2             relu   

  activate_regularizers epochs lstm_layers dropout_ratio hidden_units  \
1    mean_squared_error      0        relu            50          sgd   
2    mean_squared_error      0        relu            50          sgd   

  compile_loss gru_layers batch_window_size compile_optimizer  \
1           10          0               128              relu   
2           10          0               512              relu   

  output_activation  
1                 0  

```

You can see in the output above, the scan values appear to be one column index off, which leads to incorrect reporting and difficulty reconstructing the best parameter associations. 

This originally popped up when I realized that `best_params` is an array, leaving no real clear way of reconstructing the original parameter dictionary associations for storing the parms for replay later.

The ask is to simply offer a way of extracting the `best_params` in a format that allows restoration of the values to the original parameter keys.

BTW, thank you for this module.

**Comment by toddpi314** [comment]
This is interesting:

When I prefix the parameters with a key that forces them into the end of an alpha list (`z_`), they correctly show up in the reporting data column arrangement:

```
round_epochs                                 10
acc                         0.20000000298023224
loss                                214259280.0
val_acc                                     0.6
val_loss                            212599984.0
lr                                         0.01
yo_activate_regularizers                      0
yo_recurrent_activation                     sgd
yo_output_activation                         50
yo_hidden_units                               1
yo_lstm_layers               mean_squared_error
yo_batch_window_size                       relu
yo_compile_loss                               0
yo_gru_layers                              relu
yo_compile_optimizer                        0.2
yo_dropout_ratio                             10
yo_epochs                                   512
yo_inner_activation                        relu
Name: 1, dtype: object
```

**Comment by mikkokotila** [comment]
You're most welcome :) There was a bunch of chances related with this in 0.4.4 and 0.4.5. Could you [upgrade to 0.4.5.](https://github.com/autonomio/talos/wiki/Installation-Options#install-from-weekly) and see if that resolves your issue. 

Related with the ability to get the best_params in a dictionary, it's a good idea to be able to get a list of dictionaries with the best params for human readability. I'll create a new issue for that.

**Comment by mikkokotila** [comment]
I think this should be resolved in the latest version, so closing here.

**Comment by felixriese** [comment]
For me, it is not resolved. I installed the latest talos version this Monday with
`pip3 install git+https://github.com/autonomio/talos@daily-dev`

and unfortunately, the same problem occurs. How can I help to resolve that problem?

**Comment by mikkokotila** [comment]
@felixriese can you try one of the examples https://github.com/autonomio/talos/tree/dev#examples

Maybe to be safe, create a new environment and try the example then.

**Comment by felixriese** [comment]
**Troubleshooting example:** It is not working, misses matplotlib and after `pip install matplotlib`, there is an input error `ImportError: Python is not installed as a framework. ...`.

**Guess:** Is it possible that this problem only occurs for functional keras models? It worked with other models before and I am figuring out the difference between these models at the moment.

**Comment by mikkokotila** [comment]
@felixriese Ah, that script is expecting matplotlib to be installed in the env already. The error you get is a matplotlib error (I guess you are on Mac OSX)?

Can you check the talos version in the env you are using?

Ok, will wait for your update regarding the model. But in the more recent versions there should not be any difference, as we now treat both exactly the same and there are many users who use functional models (that seems to be popular).

**Comment by felixriese** [comment]
@mikkokotila Yes, Mac OSX. It says `talos==0.4.5` in the env of the troubleshooting example.

The error occurred on the `tensorflow/tensorflow:1.12.0-gpu-py3`, maybe that helps in the meantime.

**Comment by mikkokotila** [comment]
As a first measure, can you update to 0.4.6 that is available in dev and daily-dev now. This should not change anything regarding the issue we are tracking down, but it is a good measure nevertheless. 

Are you by any chance on Jupyter? If yes, what do you get with:

`print(talos.__version__)`

...because sometimes jupyter uses another python (and different packages) than the env where you launch it.

**Comment by felixriese** [comment]
In my docker, I've installed the latest version `0.4.6` when the problem occurred.

**Comment by felixriese** [comment]
Dict:
```python
    p = {
        "conv1_filt": [16, 32],
        "conv2_filt": [32, 64],
        "conv3_filt": [64, 128],
        "conv4_filt": [64, 128],
        "kernel_size": [3],
        "activation": ["relu"],
        "padding": ["same", "valid"],
        "fc1_units": [128],
        "fc2_units": [128],
        "losses": ["categorical_crossentropy"],
        "optimizer": ["adam", "nadam"],
        "batch_size": [16, 32, 128],
        "epochs": [40, 120],
    }
```

First 3 lines of the CSV-file:
```csv
round_epochs,val_loss,val_acc,acc,loss,kernel_size,conv4_filt,epochs,conv2_filt,activation,fc1_units,batch_size,losses,conv1_filt,conv3_filt,optimizer,fc2_units,padding
40,0.7091530537674303,0.7073013831197199,0.7286607234592087,0.6670888108251427,3,64,32,relu,32,categorical_crossentropy,40,16,128,128,128,same,adam
120,0.6819279710074719,0.7365712447924107,0.8191413053822256,0.44182159027514345,3,64,64,relu,32,categorical_crossentropy,120,32,128,128,128,valid,nadam
```

The  `Reporting()` is working without error, the output after
```
r = ta.Reporting("file.csv")
r.data
```
is the dataframe with exactly the structure of the CSV-file. -> The wrong order.

**Comment by mikkokotila** [comment]
Got it. I think that this is something else than the OP case. I have not seen such error before (I've seen where the column and label is off by one but here that's clearly not the case). 

Can you share small amount of data, or data in the same shape / type as the one you are inputting to the model, as well as your Scan command. I will try to replicate this, and try to get this fixed ASAP. I usually spend time every morning on Talos issues/fixes so it might be I can take care of it tomorrow. 

Thanks a lot for taking the time for the back and forth. No doubt we are close to resolving this for you (and getting rid of any underlying issues that are causing this).

**Comment by felixriese** [comment]
**Data:**
* `X_train, X_val': The shape of each datapoint is (256,) with values between 0 and 1 (maybe generate them with np.random.rand for testing) and I train with about 10000 datapoints.
* `y_train, y_val': I perform a classification with 4 classes and I use the LabelBinarizer from sklearn. The y-data therefore has a shape of (4,) with one value 1 and three values 0.

**Scan:**
```python
p = {
    "conv1_filt": [16, 32],
    "conv2_filt": [32, 64],
    "conv3_filt": [64, 128],
    "conv4_filt": [64, 128],
    "kernel_size": [3],
    "activation": ["relu"],
    "padding": ["same", "valid"],
    "fc1_units": [128],
    "fc2_units": [128],
    "losses": ["categorical_crossentropy"],
    "optimizer": ["adam", "nadam"],
    "batch_size": [16, 32, 128],
    "epochs": [40, 120],
}

h = ta.Scan(x=X_train, y=y_train, params=p,
            dataset_name="datasetname",
            experiment_no="1",
            model=mymodel,
            x_val=X_val, y_val=y_val
            )
```

What else do you need?

**Comment by mikkokotila** [comment]
Ah, sorry my mistake, I also need the input Keras model of course :)

**Comment by felixriese** [comment]
I added the model above :)

**Comment by mikkokotila** [comment]
Thanks for the co-operation. I've tested your model and it produces exactly the right h.data (the Scan() object dataframe) and exactly the right csv. 

I'm almost sure there is something in your system that refers to a wrong talos version. If you can create an AWS/google instance, you would be able to verify this easily by running your code there. 

Here is the code I've used to generate the data that is accepted by your model. As the first step, you could try it with your model in the system that yields the issue. Just to eradicate the doubt that the input data would somehow effect the headings.

```
import numpy as np

from keras.utils import to_categorical

data = np.random.randint(0,4,12)
data = np.array(data)
y_train = to_categorical(data)
y_val = to_categorical(data)

X_train = np.random.random((12,200))
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_val = X_train

```
Other than that, I've used your model exactly like you had provided, except for one more thing. I'm using `grid_downsample=0.02` to make the test pass instantly.

**Comment by mikkokotila** [comment]
Related with this, the most common case I'm aware of is that the model is run on a Jupyter notebook, but the `kernel spec` is messed up. So if you are on Jupyter, then the first thing to do is to make sure that `print(talos.__version__)` yields 0.4.6.

**Comment by mikkokotila** [comment]
@felixriese Having thought about this a little bit more, it seems that the following progression makes the most sense (escalating from fastest to slowest): 

FIRST

1) using the same data generator as I had used, do you get the same issue?

IF YES

2) if you are on Jupyter, do you get 0.4.6 as the version following the above instructions 

IF YES

3) share a sample of your actual data (can be with dummy values) and I will repeat in my end

**Comment by felixriese** [comment]
@mikkokotila Sorry for the delay. 

**1.** Here are the first three lines of the CSV file resulting from our test code:
```
round_epochs,val_acc,acc,loss,val_loss,batch_size,conv3_filt,optimizer,losses,activation,conv4_filt,kernel_size,conv1_filt,epochs,conv2_filt,padding,fc2_units,fc1_units
120,1.0,1.0,3.2698731956770644e-05,3.217220728402026e-05,16,64,nadam,same,categorical_crossentropy,relu,128,3,32,64,120,128,128
120,1.0,1.0,6.357862730510533e-06,6.328059953375487e-06,128,128,adam,valid,categorical_crossentropy,relu,64,3,32,32,120,128,128
```

As far as I see it, the problem is replicated.

**2.** I do not use jupyter. I included `print(ta.__version__)` into the test script and the result was `0.4.6`.

**Comment by mikkokotila** [comment]
@felixriese thanks a lot. That is really interesting.

I know this does not help with the problem, but to first get out of the way exactly what I had done.

After running the Scan: 

```
import pandas as pd
pd.read_csv('datasetname_1.csv')
```
I get: 

<img src="https://i.imgur.com/MOPLCB7.png">

The order of columns I get from reading the CSV: 

`round_epochs | val_loss | val_acc | loss | acc | conv1_filt | conv2_filt | conv3_filt | conv4_filt | kernel_size | activation | padding | fc1_units | fc2_units | losses | optimizer | batch_size | epochs`

Also if I:

```
r = ta.Reporting(h)
r.data
```
I get the same result. 

Can you give the spec to your docker container (assuming this issue is coming in the container) and I will try to replicate in a clean machine on AWS. What is your OS and OS version?

I think one thing you can still try in the effected system is to uninstall talos from the effected env and delete the talos package folder/s from all envs. Then reinstall with: 

pip install git+https://github.com/autonomio/talos@daily-dev

**Comment by felixriese** [comment]
Here the screenshot from the terminal:

![talos_screenshot](https://user-images.githubusercontent.com/17081863/51242715-019c3200-1981-11e9-9ccb-8c1fdcc8ef99.png)

As you can see, the problem still exists (e.g. padding). The columns look like that:

```python
>>> pd.read_csv("datasetname_1.csv").columns
Index(['round_epochs', 'val_acc', 'acc', 'loss', 'val_loss', 'batch_size',
       'conv3_filt', 'optimizer', 'losses', 'activation', 'conv4_filt',
       'kernel_size', 'conv1_filt', 'epochs', 'conv2_filt', 'padding',
       'fc2_units', 'fc1_units'],
      dtype='object')
```

And with Talos, it looks the same (also wrong):
![talos_screenshot2](https://user-images.githubusercontent.com/17081863/51243521-1679c500-1983-11e9-833d-1a72fb1cec29.png)

I use [this Dockerfile](https://github.com/felixriese/CNN-SoilTextureClassification/blob/master/Dockerfile) and install Talos afterwards with
```bash
pip3 install git+https://github.com/autonomio/talos@daily-dev
```
what is essentially what you are proposing.

The OS of the machine that starts the docker (is that important?) is:
```bash
>>> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
...
```

**Comment by mikkokotila** [comment]
Thanks. What is the Python version?

**Comment by felixriese** [comment]
> Thanks. What is the Python version?

As shown in the first screenshot: Python 3.5.2

**Comment by mikkokotila** [comment]
@felixriese Below I will propose a very simple solution that might just fix this issue for you.

In the interest of transparency, I will also share with you what I know so far. The problem you are suffering from is previously unknown, and it is not the same problem as OP's problem which is shifting of column headers by one (a problem related with older version of Talos). 

The line of code that this likely relates with is: 

`[_rr_out.append(key) for key in self.params.keys()]`

...where the resulting list becomes the columns after the last key from the history object (which in your case is val_loss). Right now my working theory is that for some reason in your system the order of the dictionary is changed in what seems visually an arbitrary manner. In case you would add to /utils/results.py to line 16 (before the current line 16) the following: 

`print(self.params.keys())`

...you will most likely get the a print out which is identical with the column order you are getting. Why that would happen in your system vs. any other, I'm not clear on. The good news is that if indeed this is the case, the fix might be very simple.  

### The proposed solution:

Instead of doing: 

`ta.Scan(... params=p ...) `

Try: 

```
from collections import OrderedDict
ta.Scan(... params=OrderedDict(p) ...)
```
When you do that, what happens?

**Comment by felixriese** [comment]
@mikkokotila 

The **print-statement** doesn't give an output or I was not able to produce it correctly.

The **OrderedDict** helps as far as I see it. I tested it several times, the problem occurred without the OrderedDict most (!) of the time and with the OrderedDict it did not occurr. Maybe implementing an OrderedDict in talos might be a fix (since I don't have the time and resources to test it the next days, sorry!).

**Comment by mikkokotila** [comment]
@felixriese 

Amazing. That's a huge relief, as the next steps would have become pretty involving :) Yes, I will implement OrderedDict as a default, but I have to first put some time into it as it relates with a key aspect of the mainline problem. It should be ok as it's really just retaining the order of the dict, but still better be safe than sorry. I think that by v.0.4.8 this would be incorporated. So maybe a few weeks down the road. 

I've created a new issue #172 to handle this. Given that OP's issue is resolved, as well as yours, closing here. Thank's for taking the time to go through the hoops. Great that we squashed it!

**Comment by GeneticHero** [comment]
Similar issue using talos (0.4.9)

with the model: 

def the_network(X, Y, x_val, y_val, params):

	model = Sequential()

	model.add(Dense(params['first_neuron'], input_dim=len(X[0]), activation=params['activation']))
	model.add(Dense(params['layer_one'], activation=params['activation'], kernel_initializer=params['kernel_initializer']))
	model.add(Dense(params['layer_two'], activation=params['activation'], kernel_initializer=params['kernel_initializer']))

	model.add(Dense(1, activation="sigmoid"))

	model.compile(optimizer=params['optimizer'](lr=lr_normalizer(params['lr'], params['optimizer'])), loss='mean_squared_error',
                  metrics=['mse'])

	out = model.fit(X, Y, epochs=params['epochs'], validation_split = 0.2, batch_size=params['batch_size'],  verbose=0, validation_data = (x_val, y_val) )

   	return out, model

p = {    'first_neuron': [10],
	'layer_one': [26],
	'layer_two': [10],
        'optimizer': [Adam],
	'kernel_initializer': ['lecun_uniform'],
	'lr': [3.6],
	'epochs': [1166],
        'activation': [relu],
        'batch_size': [9]
}

scan = ta.Scan(x_train, y_train, x_val = x_test, y_val = y_test, model=the_network,  grid_downsample = 1, params = OrderedDict(p), dataset_name='BkgData',  experiment_no='1')	

r = Reporting("BkgData_1.csv")
print r.data

output: 
![Selection_235](https://user-images.githubusercontent.com/50476649/57506944-f8571c80-7305-11e9-8aa2-d37291eecedd.png)

**Comment by mikepm35** [comment]
@GeneticHero @mikkokotila I had this same issue as well on v0.4.9 which has the change to ingest params as an OrderedDict.  However, this doesn't really fix the issue since if the original dict that the user defines becomes out of order then OrderedDict just maintains that "incorrect" order.  Reloading the environment does work, but what I ended up doing is explicitly defining the parameters as OrderedDict before passing to Scan().

```
ta_params = OrderedDict()
ta_params['lr'] = (0.0001, 0.01, 5)
ta_params['first_neuron'] = [4, 16, 64]
ta_params['hidden_layers'] = [0, 1, 2, 3]
ta_params['batch_size'] = [4, 32, 64]
ta_params['epochs'] = [50, 150]
ta_params['dropout'] = (0, 0.5, 3)
ta_params['shapes'] = ['brick', 'triangle']
ta_params['optimizer'] = [keras.optimizers.Adam, keras.optimizers.SGD]
ta_params['losses'] = ['categorical_crossentropy']
ta_params['activation'] = ['relu']
ta_params['last_activation'] = ['softmax']
```
